language: python

matrix:
  include:
    - python: 3.8
      dist: trusty
      sudo: false
    - python: 3.10
      dist: trusty
      sudo: xenial
    - python: 3.11
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 --max-line-length=92
  - coverage run --source=. manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-east-1"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-east-1-695197419015"
  skip_cleanup: true
  on:
    branch: main
